/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmGerenciador.java
 *
 * Created on 10/11/2014, 06:52:07
 */
package Formularios;

import Utilitarios.Conexao;
import java.awt.Color;                 //biblioteca de cores
import java.sql.Connection;             
import javax.swing.ImageIcon;          //biblioteca de umagens

/**
 *
 * @author Aluno
 */
public class frmGerenciador extends javax.swing.JFrame {
        private Connection Connection;
 
    /** Creates new form frmGerenciador */
    public frmGerenciador() {
        initComponents();
        this.getContentPane().setBackground(Color.black);  //cor de fundo do formulário
        setExtendedState(MAXIMIZED_BOTH);                  //maximização do formulário
        inserirIcone();
    }
       // método para colocar imagens a princípio nos itens de menu do formulário
       private void inserirIcone(){
            mnuAlunos.setIcon(new ImageIcon(getClass().getResource("/Icones/alunos.png")));
            mnuProf.setIcon(new ImageIcon(getClass().getResource("/Icones/professores.png")));
            mnuMat.setIcon(new ImageIcon(getClass().getResource("/Icones/ico_catalogo_completo.png")));
            mnuSair.setIcon(new ImageIcon(getClass().getResource("/Icones/sair.png")));   
       } 
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlunos = new javax.swing.JMenuItem();
        mnuProf = new javax.swing.JMenuItem();
        mnuMat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle do Sistema");
        setBackground(new java.awt.Color(102, 255, 204));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/SATELIT2.JPG"))); // NOI18N
        jLabel1.setAlignmentX(100.0F);
        jLabel1.setAlignmentY(100.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 190, 470, 326);

        jMenu1.setText("Cadastros");

        mnuAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAlunos.setText("Alunos");
        mnuAlunos.setToolTipText("Cadastrar Alunos já com RA disponível");
        mnuAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlunos);

        mnuProf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuProf.setText("Professores");
        mnuProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProf);

        mnuMat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuMat.setText("Matérias");
        jMenu1.add(mnuMat);
        jMenu1.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSair.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mnuSairAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(jMenu1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnuAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlunosActionPerformed
        frmCadAlunos formulario = new frmCadAlunos();  //instanciamento de um formulário
        formulario.setVisible(true);                   //visibilidade deste formulário
}//GEN-LAST:event_mnuAlunosActionPerformed

private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_formWindowStateChanged

private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
                frmGerenciador.this.dispose();     //fechamento do formulário
                Conexao.fecharConexao(Connection); //fechamento da conexão com a base de dados (fechar a base)
}//GEN-LAST:event_mnuSairActionPerformed

private void mnuSairAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mnuSairAncestorAdded
// TODO add your handling code here:
}//GEN-LAST:event_mnuSairAncestorAdded

    private void mnuProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfActionPerformed
//        frmProfessores formulario = new frmProfessores(); 
//        formulario.setVisible(true);
    }//GEN-LAST:event_mnuProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new frmGerenciador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuAlunos;
    private javax.swing.JMenuItem mnuMat;
    private javax.swing.JMenuItem mnuProf;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables

    //private void setMenuBar(JMenuBar jMenuBar1) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   // }
}
